name: Hous debug apk
on:
  push:
    branches:
      - feature/#162-feat-auto-emit-debug-apk
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[QA]') }}
    steps:
      - uses: actions/checkout@v2

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Create Google-Services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: |
          touch ./app/google-services.json
          echo $GOOGLE_SERVICES >> ./app/google-services.json
          cat ./app/google-services.json
      - name: Create Local Properties
        run: touch local.properties

      - name: Access Local Properties
        env:
          HOST_URI: ${{ secrets.HOST_URI }}
          KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
          KAKAO_REDIRECT_SCHEME: ${{ secrets.KAKAO_REDIRECT_SCHEME }}
          DUMMY_ACCESS_TOKEN: ${{ secrets.DUMMY_ACCEESS_TOKEN }}
          KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
        run: |
          echo HOST_URI=\"$HOST_URI\" >> local.properties
          echo KAKAO_NATIVE_APP_KEY=\"$KAKAO_NATIVE_APP_KEY\" >> local.properties
          echo KAKAO_REDIRECT_SCHEME=\"$KAKAO_REDIRECT_SCHEME\" >> local.properties
          echo DUMMY_ACCESS_TOKEN=\"$DUMMY_ACCESS_TOKEN\" >> local.properties
          echo KEYSTORE_PATH=\"KEYSTORE_PATH\" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Create Key Store
        run: echo "${{ secrets.KEYSTORE_FILE_BASE_64 }}" | base64 -d > app/keystore/debug.keystore
        
      - name: Build debug APK
        run: ./gradlew clean assembleDebug

      - uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL }}
          initial_comment: 'Hous APK ! ! !'
          file_type: 'apk'
          file_name: 'Hous.apk'
          file_path: './app/build/outputs/apk/debug/app-debug.apk'
          retries: 1
