name: Hous debug apk
on:
  push:
    branches:
      - feature/#162-feat-auto-emit-debug-apk
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - uses: MeilCli/slack-upload-file@v2
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNEL }}
          initial_comment: 'Hous APK ! ! !'
          file_type: 'apk'
          file_name: 'Hous.apk'
          file_path: './app/build/outputs/apk/debug/app-debug.apk'
